universe = vanilla
Executable = /home/eusai/4t/TTTT/TMVA/doCondorApplication.sh
Should_Transfer_Files = YES
WhenToTransferOutput = ON_EXIT
request_memory = 3072
Transfer_Input_Files = /home/eusai/4t/TTTT/TMVA/Application_FWLJMET102X_1lep2017_Oct2019_4t_02182020_step3_61var_condorLogs/nominal//TMVAClassificationApplication.C
Output = TTTo2L2Nu_hdampUP_TuneCP5_PSweights_13TeV-powheg-pythia8_ttjj_hadd.out
Error = TTTo2L2Nu_hdampUP_TuneCP5_PSweights_13TeV-powheg-pythia8_ttjj_hadd.err
Log = TTTo2L2Nu_hdampUP_TuneCP5_PSweights_13TeV-powheg-pythia8_ttjj_hadd.log
Notification = Never
Arguments = /mnt/hadoop/store/group/bruxljm/FWLJMET102X_1lep2017_Oct2019_4t_02052020_step2/nominal/ /mnt/hadoop/store/group/bruxljm/FWLJMET102X_1lep2017_Oct2019_4t_02182020_step3_61var/nominal/ TTTo2L2Nu_hdampUP_TuneCP5_PSweights_13TeV-powheg-pythia8_ttjj_hadd.root BDT /home/eusai/4t/TTTT/TMVA/Application_FWLJMET102X_1lep2017_Oct2019_4t_02182020_step3_61var_condorLogs/nominal/

Queue 1