// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.16/00       [397312]
Creator        : wzhang
Date           : Mon Feb 10 10:32:25 2020
Host           : Linux lcgapp-centos7-x86-64-25.cern.ch 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/wzhang/work/fwljmet_201905/CMSSW_10_2_10/src/TTTT/TMVA
Training events: 532594
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
IgnoreNegWeightsInTraining: "True" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "2.5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "giniindex" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
Shrinkage: "1.000000e+00" [Learning rate for BoostType=Grad algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "8" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 61
AK4HTpMETpLepPt               AK4HTpMETpLepPt               AK4HTpMETpLepPt               S_{T}                         GeV                               'F'    [620.863464355,19489.4765625]
minMleppBjet                  minMleppBjet                  minMleppBjet                  min[M(l,b)]                   GeV                               'F'    [19.0456466675,100000000]
mass_minBBdr                  mass_minBBdr                  mass_minBBdr                  M(b,b) with min[#DeltaR(b,b)] GeV                               'F'    [-1,3475.39013672]
deltaR_lepBJet_maxpt          deltaR_lepBJet_maxpt          deltaR_lepBJet_maxpt          #DeltaR(l,b)] with max[p_{T}(l,b)]                                  'F'    [-1,5.24211597443]
lepDR_minBBdr                 lepDR_minBBdr                 lepDR_minBBdr                 #DeltaR(l,bb) with min[#DeltaR(b,b)]                                  'F'    [-1,8.09948635101]
centrality                    centrality                    centrality                    Centrality                                                      'F'    [0.191080659628,0.991649210453]
deltaEta_maxBB                deltaEta_maxBB                deltaEta_maxBB                max[#Delta#eta(b,b)]                                            'F'    [-4.77932882309,1000000000]
aveCSVpt                      aveCSVpt                      aveCSVpt                      p_{T} weighted CSVv2                                            'F'    [-1.99857592583,1.03219306469]
aveBBdr                       aveBBdr                       aveBBdr                       ave[#DeltaR(b,b)]                                               'F'    [-1,5.59314870834]
FW_momentum_0                 FW_momentum_0                 FW_momentum_0                 0^{th} FW moment              GeV                               'F'    [0.999998927116,1.00000083447]
FW_momentum_1                 FW_momentum_1                 FW_momentum_1                 1^{st} FW moment              GeV                               'F'    [2.78449733742e-05,0.985110878944]
FW_momentum_2                 FW_momentum_2                 FW_momentum_2                 2^{nd} FW moment              GeV                               'F'    [0.00124633812811,0.988324344158]
FW_momentum_3                 FW_momentum_3                 FW_momentum_3                 3^{rd} FW moment              GeV                               'F'    [0.001127970987,0.934850990772]
FW_momentum_4                 FW_momentum_4                 FW_momentum_4                 4^{th} FW moment              GeV                               'F'    [0.00470097083598,0.973223030567]
FW_momentum_5                 FW_momentum_5                 FW_momentum_5                 5^{th} FW moment              GeV                               'F'    [0.00284631666727,0.924611389637]
FW_momentum_6                 FW_momentum_6                 FW_momentum_6                 6^{th} FW moment              GeV                               'F'    [0.0143310735002,0.96927601099]
mass_maxJJJpt                 mass_maxJJJpt                 mass_maxJJJpt                 M(jjj) with max[p_{T}(jjj)]   GeV                               'F'    [62.1498641968,5514.21240234]
BJetLeadPt                    BJetLeadPt                    BJetLeadPt                    p_{T}(b_{1})                  GeV                               'F'    [-99,9466.37109375]
deltaR_minBB                  deltaR_minBB                  deltaR_minBB                  min[#DeltaR(b,b)]                                               'F'    [0.128817483783,1000000000]
minDR_lepBJet                 minDR_lepBJet                 minDR_lepBJet                 min[#DeltaR(l,b)]                                               'F'    [0.400000542402,1000000000]
MT_lepMet                     MT_lepMet                     MT_lepMet                     M_{T}(lep,E_{T}^{miss})       GeV                               'F'    [60.0002632141,1160.9473877]
AK4HT                         AK4HT                         AK4HT                         H_{T}                         GeV                               'F'    [510.000061035,9684.73925781]
hemiout                       hemiout                       hemiout                       Hemiout                       GeV                               'F'    [-1,9539.85546875]
theJetLeadPt                  theJetLeadPt                  theJetLeadPt                  p_{T}(j_{1})                  GeV                               'F'    [65.6619491577,9466.37109375]
corr_met_MultiLepCalc         corr_met_MultiLepCalc         corr_met_MultiLepCalc         E_{T}^{miss}                  GeV                               'F'    [60.0000839233,9660.20800781]
leptonPt_MultiLepCalc         leptonPt_MultiLepCalc         leptonPt_MultiLepCalc         p_{T}(lep)                    GeV                               'F'    [50.0001029968,1159.61730957]
mass_lepJets0                 mass_lepJets0                 mass_lepJets0                 M(l,j_{1})                    GeV                               'F'    [33.885799408,8802.40332031]
mass_lepJets1                 mass_lepJets1                 mass_lepJets1                 M(l,j_{2})                    GeV                               'F'    [26.5588207245,2648.0559082]
mass_lepJets2                 mass_lepJets2                 mass_lepJets2                 M(l,j_{3})                    GeV                               'F'    [21.8447246552,2341.38037109]
MT2bb                         MT2bb                         MT2bb                         MT2bb                         GeV                               'F'    [0,804.370605469]
mass_lepBJet0                 mass_lepBJet0                 mass_lepBJet0                 M(l,b_{1})                    GeV                               'F'    [-1,8802.40332031]
mass_lepBJet_mindr            mass_lepBJet_mindr            mass_lepBJet_mindr            M(l,b) with min[#DeltaR(l,b)] GeV                               'F'    [-1,8802.40332031]
secondJetPt                   secondJetPt                   secondJetPt                   p_{T}(j_{2})                  GeV                               'F'    [34.7870407104,1684.95617676]
fifthJetPt                    fifthJetPt                    fifthJetPt                    p_{T}(j_{5})                  GeV                               'F'    [-1,517.64251709]
sixthJetPt                    sixthJetPt                    sixthJetPt                    p_{T}(j_{6})                  GeV                               'F'    [-1,402.537200928]
PtFifthJet                    PtFifthJet                    PtFifthJet                    5^{th} jet p_{T}              GeV                               'F'    [-1,1919.89807129]
mass_minLLdr                  mass_minLLdr                  mass_minLLdr                  M(j,j) with min[#DeltaR(j,j)], j #neq bGeV                               'F'    [-1,5464.84570312]
mass_maxBBmass                mass_maxBBmass                mass_maxBBmass                max[M(b,b)]                   GeV                               'F'    [-1,4590.59570312]
deltaR_lepJetInMinMljet       deltaR_lepJetInMinMljet       deltaR_lepJetInMinMljet       #DeltaR(l,j) with min M(l, j)                                   'F'    [0.400000542402,4.44488239288]
deltaPhi_lepJetInMinMljet     deltaPhi_lepJetInMinMljet     deltaPhi_lepJetInMinMljet     #DeltaPhi(l,j) with min M(l, j)                                  'F'    [-3.14147758484,3.14156460762]
deltaR_lepbJetInMinMlb        deltaR_lepbJetInMinMlb        deltaR_lepbJetInMinMlb        #DeltaR(l,b) with min M(l, b)                                   'F'    [-99,5.32525253296]
deltaPhi_lepbJetInMinMlb      deltaPhi_lepbJetInMinMlb      deltaPhi_lepbJetInMinMlb      #DeltaPhi(l,b) with min M(l, b)                                  'F'    [-99,3.1414501667]
M_allJet_W                    M_allJet_W                    M_allJet_W                    M(allJets, leptoninc W)       GeV                               'F'    [515.022277832,72629]
HT_bjets                      HT_bjets                      HT_bjets                      HT(bjets)                     GeV                               'F'    [-10,9456.37109375]
ratio_HTdHT4leadjets          ratio_HTdHT4leadjets          ratio_HTdHT4leadjets          HT/HT(4 leading jets)                                           'F'    [1.00794661045,2.62445449829]
csvJet3                       csvJet3                       csvJet3                       DeepCSV(3rdPtJet)                                               'F'    [-2,0.999928772449]
csvJet4                       csvJet4                       csvJet4                       DeepCSV(4thPtJet)                                               'F'    [-2,0.999970436096]
thirdcsvb_bb                  thirdcsvb_bb                  thirdcsvb_bb                  DeepCSV(3rdDeepCSVJet)                                          'F'    [-2,0.999268293381]
fourthcsvb_bb                 fourthcsvb_bb                 fourthcsvb_bb                 DeepCSV(4thDeepCSVJet)                                          'F'    [-2,0.996882855892]
NJets_JetSubCalc              NJets_JetSubCalc              NJets_JetSubCalc              AK4 jet multiplicity                                            'I'    [4,19]
HT_2m                         HT_2m                         HT_2m                         HTwoTwoPtBjets                GeV                               'F'    [-100,4151.7734375]
Sphericity                    Sphericity                    Sphericity                    Sphericity                    Sphericity                        'F'    [3.60423564416e-06,0.947829902172]
Aplanarity                    Aplanarity                    Aplanarity                    Aplanarity                    Aplanarity                        'F'    [2.15262332404e-07,0.445236414671]
BDTtrijet1                    BDTtrijet1                    BDTtrijet1                    trijet1 discriminator                                           'F'    [-1,0.999728739262]
BDTtrijet2                    BDTtrijet2                    BDTtrijet2                    trijet2 discriminator                                           'F'    [-1,0.996382951736]
BDTtrijet3                    BDTtrijet3                    BDTtrijet3                    trijet3 discriminator                                           'F'    [-1,0.987466156483]
BDTtrijet4                    BDTtrijet4                    BDTtrijet4                    trijet4 discriminator                                           'F'    [-1,0.941090404987]
NresolvedTops1pFake           NresolvedTops1pFake           NresolvedTops1pFake           resolvedTop multiplicity                                        'F'    [0,3]
NJetsTtagged                  NJetsTtagged                  NJetsTtagged                  top multiplicity                                                'F'    [0,4]
NJetsWtagged                  NJetsWtagged                  NJetsWtagged                  W multiplicity                                                  'F'    [0,4]
NJetsCSVwithSF_JetSubCalc     NJetsCSVwithSF_JetSubCalc     NJetsCSVwithSF_JetSubCalc     bjet multiplicity                                               'F'    [0,11]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 61 )
   {
      // the training input variables
      const char* inputVars[] = { "AK4HTpMETpLepPt", "minMleppBjet", "mass_minBBdr", "deltaR_lepBJet_maxpt", "lepDR_minBBdr", "centrality", "deltaEta_maxBB", "aveCSVpt", "aveBBdr", "FW_momentum_0", "FW_momentum_1", "FW_momentum_2", "FW_momentum_3", "FW_momentum_4", "FW_momentum_5", "FW_momentum_6", "mass_maxJJJpt", "BJetLeadPt", "deltaR_minBB", "minDR_lepBJet", "MT_lepMet", "AK4HT", "hemiout", "theJetLeadPt", "corr_met_MultiLepCalc", "leptonPt_MultiLepCalc", "mass_lepJets0", "mass_lepJets1", "mass_lepJets2", "MT2bb", "mass_lepBJet0", "mass_lepBJet_mindr", "secondJetPt", "fifthJetPt", "sixthJetPt", "PtFifthJet", "mass_minLLdr", "mass_maxBBmass", "deltaR_lepJetInMinMljet", "deltaPhi_lepJetInMinMljet", "deltaR_lepbJetInMinMlb", "deltaPhi_lepbJetInMinMlb", "M_allJet_W", "HT_bjets", "ratio_HTdHT4leadjets", "csvJet3", "csvJet4", "thirdcsvb_bb", "fourthcsvb_bb", "NJets_JetSubCalc", "HT_2m", "Sphericity", "Aplanarity", "BDTtrijet1", "BDTtrijet2", "BDTtrijet3", "BDTtrijet4", "NresolvedTops1pFake", "NJetsTtagged", "NJetsWtagged", "NJetsCSVwithSF_JetSubCalc" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;
      fVmin[19] = 0;
      fVmax[19] = 0;
      fVmin[20] = 0;
      fVmax[20] = 0;
      fVmin[21] = 0;
      fVmax[21] = 0;
      fVmin[22] = 0;
      fVmax[22] = 0;
      fVmin[23] = 0;
      fVmax[23] = 0;
      fVmin[24] = 0;
      fVmax[24] = 0;
      fVmin[25] = 0;
      fVmax[25] = 0;
      fVmin[26] = 0;
      fVmax[26] = 0;
      fVmin[27] = 0;
      fVmax[27] = 0;
      fVmin[28] = 0;
      fVmax[28] = 0;
      fVmin[29] = 0;
      fVmax[29] = 0;
      fVmin[30] = 0;
      fVmax[30] = 0;
      fVmin[31] = 0;
      fVmax[31] = 0;
      fVmin[32] = 0;
      fVmax[32] = 0;
      fVmin[33] = 0;
      fVmax[33] = 0;
      fVmin[34] = 0;
      fVmax[34] = 0;
      fVmin[35] = 0;
      fVmax[35] = 0;
      fVmin[36] = 0;
      fVmax[36] = 0;
      fVmin[37] = 0;
      fVmax[37] = 0;
      fVmin[38] = 0;
      fVmax[38] = 0;
      fVmin[39] = 0;
      fVmax[39] = 0;
      fVmin[40] = 0;
      fVmax[40] = 0;
      fVmin[41] = 0;
      fVmax[41] = 0;
      fVmin[42] = 0;
      fVmax[42] = 0;
      fVmin[43] = 0;
      fVmax[43] = 0;
      fVmin[44] = 0;
      fVmax[44] = 0;
      fVmin[45] = 0;
      fVmax[45] = 0;
      fVmin[46] = 0;
      fVmax[46] = 0;
      fVmin[47] = 0;
      fVmax[47] = 0;
      fVmin[48] = 0;
      fVmax[48] = 0;
      fVmin[49] = 0;
      fVmax[49] = 0;
      fVmin[50] = 0;
      fVmax[50] = 0;
      fVmin[51] = 0;
      fVmax[51] = 0;
      fVmin[52] = 0;
      fVmax[52] = 0;
      fVmin[53] = 0;
      fVmax[53] = 0;
      fVmin[54] = 0;
      fVmax[54] = 0;
      fVmin[55] = 0;
      fVmax[55] = 0;
      fVmin[56] = 0;
      fVmax[56] = 0;
      fVmin[57] = 0;
      fVmax[57] = 0;
      fVmin[58] = 0;
      fVmax[58] = 0;
      fVmin[59] = 0;
      fVmax[59] = 0;
      fVmin[60] = 0;
      fVmax[60] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'F';
      fType[21] = 'F';
      fType[22] = 'F';
      fType[23] = 'F';
      fType[24] = 'F';
      fType[25] = 'F';
      fType[26] = 'F';
      fType[27] = 'F';
      fType[28] = 'F';
      fType[29] = 'F';
      fType[30] = 'F';
      fType[31] = 'F';
      fType[32] = 'F';
      fType[33] = 'F';
      fType[34] = 'F';
      fType[35] = 'F';
      fType[36] = 'F';
      fType[37] = 'F';
      fType[38] = 'F';
      fType[39] = 'F';
      fType[40] = 'F';
      fType[41] = 'F';
      fType[42] = 'F';
      fType[43] = 'F';
      fType[44] = 'F';
      fType[45] = 'F';
      fType[46] = 'F';
      fType[47] = 'F';
      fType[48] = 'F';
      fType[49] = 'I';
      fType[50] = 'F';
      fType[51] = 'F';
      fType[52] = 'F';
      fType[53] = 'F';
      fType[54] = 'F';
      fType[55] = 'F';
      fType[56] = 'F';
      fType[57] = 'F';
      fType[58] = 'F';
      fType[59] = 'F';
      fType[60] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[61];
   double fVmax[61];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[61];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.476982583238858);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.520877, 0, 1, 0.720034,-99) , 
NN(
0, 
0, 
-1, 0.424655, 0, -1, 0.276175,-99) , 
47, 0.285078, 0, 0, 0.500185,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.477333);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.615932, 0, 1, 0.730811,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57137,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.229033,-99) , 
54, 0.614609, 0, 0, 0.324145,-99) , 
60, 2.14286, 0, 0, 0.497988,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.370978);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.8046, 0, 1, 0.70163,-99) , 
NN(
0, 
0, 
-1, 0.330202, 0, -1, 0.337973,-99) , 
48, 0.140237, 0, 0, 0.479352,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.308726);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.710987, 0, 1, 0.670015,-99) , 
NN(
0, 
0, 
-1, 6, 0, -1, 0.365579,-99) , 
60, 2.14286, 0, 0, 0.495741,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.323864);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.427979, 0, 1, 0.645395,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567649,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.290936,-99) , 
21, 946.894, 0, 0, 0.372727,-99) , 
54, 0.330362, 0, 0, 0.506958,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.267863);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.710987, 0, 1, 0.671655,-99) , 
NN(
0, 
0, 
-1, 992.93, 0, -1, 0.390806,-99) , 
47, 0.427848, 0, 0, 0.488037,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.235506);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.710987, 0, 1, 0.65557,-99) , 
NN(
0, 
0, 
-1, 6, 0, -1, 0.409803,-99) , 
33, 73.0918, 0, 0, 0.505392,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.28975);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.135695, 0, 1, 0.720969,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.645662,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391492,-99) , 
20, 164.852, 0, 0, 0.443825,-99) , 
54, 0.805324, 0, 0, 0.509388,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.219602);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.674663,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480619,-99) , 
43, 292.692, 0, 0, 0.561133,-99) , 
NN(
0, 
0, 
-1, 151.386, 0, -1, 0.25349,-99) , 
34, 12.6457, 0, 0, 0.515264,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.186249);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.228876, 0, 1, 0.567477,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510748,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.201466,-99) , 
31, 151.386, 0, 0, 0.266971,-99) , 
49, 6, 0, 0, 0.524045,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.234773);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.834586, 0, 1, 0.755293,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.641873,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419712,-99) , 
47, 0.570713, 0, 0, 0.467161,-99) , 
55, 0.135267, 0, 0, 0.506033,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.205327);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.710494, 0, 1, 0.619129,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519212,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.340279,-99) , 
54, 0.235001, 0, 0, 0.434146,-99) , 
0, 1061.08, 0, 0, 0.519234,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.216069);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.24819, 0, 1, 0.657617,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.609927,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415145,-99) , 
20, 157.965, 0, 0, 0.459452,-99) , 
49, 9, 0, 0, 0.50622,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.166125);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.282568, 0, 1, 0.576003,-99) , 
NN(
0, 
0, 
-1, 30.3791, 0, -1, 0.407747,-99) , 
33, 58.9056, 0, 0, 0.510732,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.229668);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 164.542, 0, 1, 0.700625,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.661311,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41876,-99) , 
48, 0.28181, 0, 0, 0.462995,-99) , 
31, 172.24, 0, 0, 0.501581,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.216648);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.613002,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418977,-99) , 
34, 18.2161, 0, 0, 0.586334,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555783,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.375109,-99) , 
54, 0.710465, 0, 0, 0.42961,-99) , 
30, 159.07, 0, 0, 0.51948,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.167234);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.766249,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570929,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432615,-99) , 
24, 118.344, 0, 0, 0.49584,-99) , 
55, 0.419084, 0, 0, 0.514814,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.17447);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.142857, 0, 1, 0.688204,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554287,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417012,-99) , 
20, 112.426, 0, 0, 0.483561,-99) , 
47, 0.71353, 0, 0, 0.513255,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.164948);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.615571,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491773,-99) , 
22, 506.454, 0, 0, 0.560683,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582933,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389065,-99) , 
47, 0.570551, 0, 0, 0.426504,-99) , 
30, 140.217, 0, 0, 0.511527,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.112392);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.658452,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485917,-99) , 
31, 151.386, 0, 0, 0.522098,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.173228,-99) , 
33, 18.621, 0, 0, 0.507764,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.136917);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.704864,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.633326,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468802,-99) , 
31, 154.571, 0, 0, 0.502256,-99) , 
55, 0.230336, 0, 0, 0.523549,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0973824);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 141.9, 0, 1, 0.539142,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.236161,-99) , 
33, 20.1389, 0, 0, 0.526472,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.141853);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.900548, 0, 1, 0.551865,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558802,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.3568,-99) , 
31, 154.571, 0, 0, 0.402714,-99) , 
47, 0.142078, 0, 0, 0.513436,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.12665);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.588688, 0, 1, 0.668091,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.667725,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465056,-99) , 
29, 118.677, 0, 0, 0.484294,-99) , 
60, 3.42857, 0, 0, 0.507837,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.072684);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 969.291, 0, 1, 0.687934,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504274,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.2385,-99) , 
33, 23.6973, 0, 0, 0.492037,-99) , 
54, 0.901096, 0, 0, 0.515022,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.133922);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 176.564, 0, 1, 0.552451,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559557,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401643,-99) , 
29, 94.3096, 0, 0, 0.432343,-99) , 
54, 0.0451877, 0, 0, 0.508269,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.135426);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.297267, 0, 1, 0.656169,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599158,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451898,-99) , 
58, 0.190476, 0, 0, 0.474355,-99) , 
54, 0.901096, 0, 0, 0.495049,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.106216);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.142857, 0, 1, 0.644291,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.666573,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474231,-99) , 
20, 216.874, 0, 0, 0.490646,-99) , 
47, 0.713624, 0, 0, 0.512464,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0779411);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.6101,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497936,-99) , 
20, 145.861, 0, 0, 0.527862,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.257224,-99) , 
33, 17.5426, 0, 0, 0.517639,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0897516);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.808762, 0, 1, 0.685114,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.653799,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483185,-99) , 
55, 0.229873, 0, 0, 0.501109,-99) , 
20, 217.278, 0, 0, 0.517308,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.155324);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582652,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449307,-99) , 
0, 817.309, 0, 0, 0.557476,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584064,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422585,-99) , 
31, 199.427, 0, 0, 0.443825,-99) , 
51, 0.176182, 0, 0, 0.52853,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0977765);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 188.791, 0, 1, 0.540805,-99) , 
NN(
0, 
0, 
-1, 1.67519, 0, -1, 0.386187,-99) , 
53, 0.523538, 0, 0, 0.524013,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.117397);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564568,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470523,-99) , 
30, 140.217, 0, 0, 0.530666,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.273627,-99) , 
33, 23.6973, 0, 0, 0.521071,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.105482);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.65174,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56203,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466659,-99) , 
29, 71.9608, 0, 0, 0.495053,-99) , 
49, 10, 0, 0, 0.510263,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0946738);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 139.112, 0, 1, 0.532199,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572282,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389787,-99) , 
0, 1521.82, 0, 0, 0.423955,-99) , 
52, 0.0208751, 0, 0, 0.509308,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.107252);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.694893,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494335,-99) , 
20, 100.951, 0, 0, 0.599403,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.601753,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46705,-99) , 
54, 0.900548, 0, 0, 0.482564,-99) , 
24, 181.471, 0, 0, 0.505498,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0915278);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 180.016, 0, 1, 0.536389,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512294,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.367415,-99) , 
3, 1.59543, 0, 0, 0.428463,-99) , 
33, 48.3945, 0, 0, 0.514458,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.100244);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.638281,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532775,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449499,-99) , 
3, 1.35694, 0, 0, 0.490327,-99) , 
48, 0.42559, 0, 0, 0.502817,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0740185);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.65905,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513537,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.377327,-99) , 
48, 0.0363962, 0, 0, 0.496052,-99) , 
47, 0.856446, 0, 0, 0.507697,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.112335);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.674901,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491056,-99) , 
20, 108.983, 0, 0, 0.576093,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538836,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450316,-99) , 
52, 0.0835009, 0, 0, 0.476501,-99) , 
24, 164.271, 0, 0, 0.500509,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0992679);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.142857, 0, 1, 0.597602,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520216,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410597,-99) , 
48, 0.0598349, 0, 0, 0.486343,-99) , 
47, 0.713477, 0, 0, 0.501988,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0880592);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.639197,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.600169,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468961,-99) , 
20, 206.947, 0, 0, 0.481536,-99) , 
55, 0.419619, 0, 0, 0.491243,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0875104);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.574743, 0, 1, 0.605224,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571642,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471615,-99) , 
58, 0.190476, 0, 0, 0.486208,-99) , 
60, 3.14286, 0, 0, 0.501309,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.113255);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.609184,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484534,-99) , 
24, 104.396, 0, 0, 0.549594,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554919,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45306,-99) , 
31, 138.556, 0, 0, 0.477295,-99) , 
20, 112.426, 0, 0, 0.512407,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0608036);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 176.688, 0, 1, 0.522238,-99) , 
NN(
0, 
0, 
-1, 1.55052, 0, -1, 0.414755,-99) , 
53, 0.618651, 0, 0, 0.508374,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0748174);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 157.259, 0, 1, 0.531208,-99) , 
NN(
0, 
0, 
-1, 1222.06, 0, -1, 0.436258,-99) , 
16, 581.394, 1, 0, 0.513314,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0586813);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 150.149, 0, 1, 0.578189,-99) , 
NN(
0, 
0, 
-1, 0.142494, 0, -1, 0.482206,-99) , 
24, 181.471, 0, 0, 0.500503,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.109457);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.638122,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48257,-99) , 
24, 120.736, 0, 0, 0.556837,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595376,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459223,-99) , 
49, 10, 0, 0, 0.472617,-99) , 
20, 141.9, 0, 0, 0.496983,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0501366);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.64306,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510565,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.340325,-99) , 
33, 20.1389, 0, 0, 0.503941,-99) , 
47, 0.856338, 0, 0, 0.513474,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0878544);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 154.571, 0, 1, 0.541818,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523325,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435933,-99) , 
20, 125.495, 0, 0, 0.470352,-99) , 
5, 0.536073, 0, 0, 0.518813,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0723915);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.606565,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575099,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476536,-99) , 
29, 107.941, 0, 0, 0.488467,-99) , 
48, 0.425602, 0, 0, 0.498329,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0732023);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.626764,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521406,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455554,-99) , 
29, 29.7589, 0, 0, 0.497469,-99) , 
47, 0.856348, 0, 0, 0.506475,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0286636);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.630122,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500427,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.340903,-99) , 
33, 20.1389, 0, 0, 0.494274,-99) , 
55, 0.414876, 0, 0, 0.502828,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0683216);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.628847,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592825,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477632,-99) , 
22, 907.653, 0, 0, 0.486434,-99) , 
55, 0.419619, 0, 0, 0.495389,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0847327);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531453,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.357438,-99) , 
33, 13.3479, 0, 0, 0.525427,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521752,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410582,-99) , 
21, 1383.79, 0, 0, 0.438442,-99) , 
16, 581.394, 1, 0, 0.509124,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0700646);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 160.505, 0, 1, 0.522378,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523767,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428076,-99) , 
20, 141.9, 0, 0, 0.453762,-99) , 
37, 172.24, 0, 0, 0.498774,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0452476);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.622723,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497391,-99) , 
0, 970.443, 0, 0, 0.573623,-99) , 
NN(
0, 
0, 
-1, 0.047477, 0, -1, 0.483916,-99) , 
54, 0.900548, 0, 0, 0.493738,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0681807);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527722,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470046,-99) , 
51, 0.227133, 0, 0, 0.507553,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.302512,-99) , 
33, 23.6973, 0, 0, 0.500836,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0365579);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.630297,-99) , 
NN(
0, 
0, 
-1, 34.9902, 0, -1, 0.487385,-99) , 
29, 143.922, 0, 0, 0.494253,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0483812);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576082,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493743,-99) , 
43, 453.574, 0, 0, 0.507265,-99) , 
NN(
0, 
0, 
-1, 1.15585, 0, -1, 0.371009,-99) , 
53, 0.142589, 0, 0, 0.499369,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0747341);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 157.259, 0, 1, 0.530013,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559634,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457297,-99) , 
43, 494.112, 0, 0, 0.471231,-99) , 
20, 108.983, 0, 0, 0.501458,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0568325);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 751.187, 0, 1, 0.575183,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506065,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427694,-99) , 
16, 540.669, 1, 0, 0.489687,-99) , 
58, 0.190476, 0, 0, 0.502799,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0501546);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.76382, 0, 1, 0.516897,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535392,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.305557,-99) , 
44, 1.14162, 0, 0, 0.391692,-99) , 
33, 36.1089, 0, 0, 0.508235,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0660735);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594947,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515805,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459792,-99) , 
3, 1.37447, 0, 0, 0.486891,-99) , 
47, 0.856446, 0, 0, 0.494339,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0747329);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 112.426, 0, 1, 0.562309,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544889,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471264,-99) , 
47, 0.713521, 0, 0, 0.481752,-99) , 
24, 176.689, 0, 0, 0.497878,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0374556);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608171,-99) , 
NN(
0, 
0, 
-1, 20.1389, 0, -1, 0.487423,-99) , 
55, 0.419084, 0, 0, 0.49518,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.042876);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.2728, 0, 1, 0.539744,-99) , 
NN(
0, 
0, 
-1, 0.142577, 0, -1, 0.485703,-99) , 
59, 0.142857, 0, 0, 0.500841,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0722046);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599093,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468952,-99) , 
16, 190.177, 0, 0, 0.571667,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536616,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478534,-99) , 
10, 0.234571, 0, 0, 0.498902,-99) , 
5, 0.762817, 0, 0, 0.510526,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0529794);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567008,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464873,-99) , 
49, 6, 0, 0, 0.5496,-99) , 
NN(
0, 
0, 
-1, 0.523538, 0, -1, 0.488687,-99) , 
5, 0.688031, 0, 0, 0.50705,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0615437);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549861,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494876,-99) , 
7, 0.743406, 1, 0, 0.521396,-99) , 
NN(
0, 
0, 
-1, 0.261999, 1, -1, 0.4146,-99) , 
53, 0.237927, 0, 0, 0.51406,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0392041);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.419619, 0, 1, 0.514918,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.345583,-99) , 
33, 23.6973, 0, 0, 0.509245,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0765123);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537601,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482252,-99) , 
5, 0.537503, 0, 0, 0.519462,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525966,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42764,-99) , 
37, 303.429, 0, 0, 0.455798,-99) , 
47, 0.142261, 0, 0, 0.503335,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0487021);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.605714,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586441,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48698,-99) , 
29, 125.746, 0, 0, 0.494559,-99) , 
55, 0.419619, 0, 0, 0.501855,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0304391);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.425229, 0, 1, 0.511182,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390187,-99) , 
53, -0.904775, 0, 0, 0.506234,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0416951);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 149.71, 0, 1, 0.515218,-99) , 
NN(
0, 
0, 
-1, 0.0201152, 0, -1, 0.458029,-99) , 
8, 1.51168, 0, 0, 0.50321,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0562141);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548463,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489357,-99) , 
20, 141.901, 0, 0, 0.506116,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523798,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.325842,-99) , 
44, 1.13872, 0, 0, 0.401012,-99) , 
33, 36.1292, 0, 0, 0.498746,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0334324);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.600632,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506456,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406735,-99) , 
53, 0.0473734, 0, 0, 0.501257,-99) , 
55, 0.413787, 0, 0, 0.507605,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0371317);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569336,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494636,-99) , 
54, 0.900548, 0, 0, 0.503517,-99) , 
NN(
0, 
0, 
-1, 397, 0, -1, 0.389126,-99) , 
53, 0.142589, 0, 0, 0.496989,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0870222);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541524,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45917,-99) , 
16, 190.749, 0, 0, 0.52043,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540372,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450495,-99) , 
58, 0.190476, 0, 0, 0.466728,-99) , 
16, 445.577, 1, 0, 0.503475,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0413492);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.598216,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505634,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423642,-99) , 
48, 0.0370557, 0, 0, 0.495131,-99) , 
47, 0.856338, 0, 0, 0.502498,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0536099);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555407,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485783,-99) , 
24, 181.472, 0, 0, 0.498697,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.327237,-99) , 
33, 23.6973, 0, 0, 0.493105,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0374765);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595724,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5035,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423857,-99) , 
48, 0.0370557, 0, 0, 0.493253,-99) , 
47, 0.856177, 0, 0, 0.500526,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0381288);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.4842, 0, 1, 0.512166,-99) , 
NN(
0, 
0, 
-1, 90.9521, 1, -1, 0.454939,-99) , 
52, 0.0208765, 0, 0, 0.500182,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0564951);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570641,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55224,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479483,-99) , 
31, 199.427, 0, 0, 0.488202,-99) , 
48, 0.425602, 0, 0, 0.495141,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0333864);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.764961, 0, 1, 0.510361,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510893,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.357166,-99) , 
11, 0.327329, 1, 0, 0.431588,-99) , 
33, 38.9371, 0, 0, 0.503096,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0648164);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608625,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456162,-99) , 
52, 0.0159566, 0, 0, 0.571205,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567157,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481615,-99) , 
49, 10, 0, 0, 0.490605,-99) , 
10, 0.417765, 0, 0, 0.500914,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0691094);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593303,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492195,-99) , 
30, 122.585, 0, 0, 0.553791,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543115,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477882,-99) , 
31, 151.191, 0, 0, 0.492167,-99) , 
26, 200.043, 1, 0, 0.506625,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0383441);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.609286,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508076,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394761,-99) , 
53, 0.237722, 0, 0, 0.500836,-99) , 
38, 2.28344, 0, 0, 0.506406,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0431676);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535211,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489509,-99) , 
7, 0.599277, 1, 0, 0.502879,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379599,-99) , 
53, -0.904775, 0, 0, 0.498259,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0483061);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.94092, 0, 1, 0.536957,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5706,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48717,-99) , 
50, 1074.87, 0, 0, 0.49483,-99) , 
10, 0.234606, 0, 0, 0.508258,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0603341);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568073,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465165,-99) , 
53, 0.909928, 0, 0, 0.550194,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548281,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483011,-99) , 
47, 0.71353, 0, 0, 0.492123,-99) , 
55, -0.905394, 0, 0, 0.504567,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0553735);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 549.583, 0, 1, 0.527697,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559697,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476713,-99) , 
38, 1.53008, 0, 0, 0.486535,-99) , 
25, 102.839, 1, 0, 0.51201,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0312362);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.10267, 0, 1, 0.510863,-99) , 
NN(
0, 
0, 
-1, 45.8868, 0, -1, 0.417402,-99) , 
14, 0.349715, 1, 0, 0.504674,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0347939);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565953,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493957,-99) , 
20, 188.791, 0, 0, 0.502332,-99) , 
NN(
0, 
0, 
-1, 0.926203, 0, -1, 0.421539,-99) , 
53, 0.237874, 0, 0, 0.496927,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0376141);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.18828, 0, 1, 0.59225,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506259,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384285,-99) , 
33, 34.0383, 0, 0, 0.500268,-99) , 
24, 242.207, 0, 0, 0.508441,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0586184);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519906,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40775,-99) , 
16, 1100.64, 1, 0, 0.515513,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576722,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455813,-99) , 
4, 3.24553, 0, 0, 0.468423,-99) , 
22, 422.009, 0, 0, 0.503122,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0316891);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55171,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495058,-99) , 
20, 182.525, 0, 0, 0.50275,-99) , 
NN(
0, 
0, 
-1, 1.45037, 0, -1, 0.41724,-99) , 
16, 876.299, 1, 0, 0.497308,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0289622);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 735.522, 0, 1, 0.553398,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501468,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.396991,-99) , 
26, 691.546, 1, 0, 0.495278,-99) , 
58, 0.142857, 0, 0, 0.50413,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0590013);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.330384, 0, 1, 0.545531,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526841,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473345,-99) , 
24, 143.554, 0, 0, 0.488275,-99) , 
0, 1501.99, 0, 0, 0.496668,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.028773);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569313,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497355,-99) , 
54, 0.900517, 0, 0, 0.505481,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376179,-99) , 
13, 0.425756, 1, 0, 0.500694,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
            retval = GetMvaValue__( inputValues );
      }

      return retval;
   }
