universe = vanilla
Executable = /user_data/jlee/TTTT/CMSSW_9_4_6_patch1/src/step2_topxsec/TMVA/doCondorClassification.sh
Should_Transfer_Files = YES
WhenToTransferOutput = ON_EXIT
request_memory = 3072
Output = BDT_BigComb_55vars_mDepth3.out
Error = BDT_BigComb_55vars_mDepth3.err
Log = BDT_BigComb_55vars_mDepth3.log
Notification = Never
Arguments = /user_data/jlee/TTTT/CMSSW_9_4_6_patch1/src/step2_topxsec/TMVA BDT_BigComb_55vars_mDepth3 BDT BigComb 1000 3

Queue 1