// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.16/00       [397312]
Creator        : wzhang
Date           : Fri Feb 14 15:30:25 2020
Host           : Linux lcgapp-centos7-x86-64-25.cern.ch 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/wzhang/work/fwljmet_201905/CMSSW_10_2_10/src/TTTT/TMVA
Training events: 477374
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
IgnoreNegWeightsInTraining: "True" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "2.5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "giniindex" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
Shrinkage: "1.000000e+00" [Learning rate for BoostType=Grad algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "8" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 61
AK4HTpMETpLepPt               AK4HTpMETpLepPt               AK4HTpMETpLepPt               S_{T}                         GeV                               'F'    [620.863464355,5394.64697266]
minMleppBjet                  minMleppBjet                  minMleppBjet                  min[M(l,b)]                   GeV                               'F'    [19.0305919647,1259.36608887]
mass_minBBdr                  mass_minBBdr                  mass_minBBdr                  M(b,b) with min[#DeltaR(b,b)] GeV                               'F'    [16.337934494,3528.24145508]
deltaR_lepBJet_maxpt          deltaR_lepBJet_maxpt          deltaR_lepBJet_maxpt          #DeltaR(l,b)] with max[p_{T}(l,b)]                                  'F'    [0.400014430285,5.17334699631]
lepDR_minBBdr                 lepDR_minBBdr                 lepDR_minBBdr                 #DeltaR(l,bb) with min[#DeltaR(b,b)]                                  'F'    [0.00128833216149,8.09948635101]
centrality                    centrality                    centrality                    Centrality                                                      'F'    [0.197259142995,0.994023859501]
deltaEta_maxBB                deltaEta_maxBB                deltaEta_maxBB                max[#Delta#eta(b,b)]                                            'F'    [-4.77932882309,4.78888940811]
aveCSVpt                      aveCSVpt                      aveCSVpt                      p_{T} weighted CSVv2                                            'F'    [-1.99784183502,1.01502108574]
aveBBdr                       aveBBdr                       aveBBdr                       ave[#DeltaR(b,b)]                                               'F'    [0.395664989948,5.6101307869]
FW_momentum_0                 FW_momentum_0                 FW_momentum_0                 0^{th} FW moment              GeV                               'F'    [0.999998927116,1.00000095367]
FW_momentum_1                 FW_momentum_1                 FW_momentum_1                 1^{st} FW moment              GeV                               'F'    [2.44622915488e-05,0.975371956825]
FW_momentum_2                 FW_momentum_2                 FW_momentum_2                 2^{nd} FW moment              GeV                               'F'    [0.000827223469969,0.979112863541]
FW_momentum_3                 FW_momentum_3                 FW_momentum_3                 3^{rd} FW moment              GeV                               'F'    [0.001127970987,0.872204780579]
FW_momentum_4                 FW_momentum_4                 FW_momentum_4                 4^{th} FW moment              GeV                               'F'    [0.00470097083598,0.933849930763]
FW_momentum_5                 FW_momentum_5                 FW_momentum_5                 5^{th} FW moment              GeV                               'F'    [0.00284631666727,0.870751857758]
FW_momentum_6                 FW_momentum_6                 FW_momentum_6                 6^{th} FW moment              GeV                               'F'    [0.0145080490038,0.881440460682]
mass_maxJJJpt                 mass_maxJJJpt                 mass_maxJJJpt                 M(jjj) with max[p_{T}(jjj)]   GeV                               'F'    [62.1498641968,4947.83300781]
BJetLeadPt                    BJetLeadPt                    BJetLeadPt                    p_{T}(b_{1})                  GeV                               'F'    [30.2089653015,2088.51611328]
deltaR_minBB                  deltaR_minBB                  deltaR_minBB                  min[#DeltaR(b,b)]                                               'F'    [0.230966866016,5.6101307869]
minDR_lepBJet                 minDR_lepBJet                 minDR_lepBJet                 min[#DeltaR(l,b)]                                               'F'    [0.400013953447,4.8167219162]
MT_lepMet                     MT_lepMet                     MT_lepMet                     M_{T}(lep,E_{T}^{miss})       GeV                               'F'    [60.0001678467,1105.20239258]
AK4HT                         AK4HT                         AK4HT                         H_{T}                         GeV                               'F'    [510.000152588,4613.43164062]
hemiout                       hemiout                       hemiout                       Hemiout                       GeV                               'F'    [-1,2759.16552734]
theJetLeadPt                  theJetLeadPt                  theJetLeadPt                  p_{T}(j_{1})                  GeV                               'F'    [66.3698883057,2528.76635742]
corr_met_MultiLepCalc         corr_met_MultiLepCalc         corr_met_MultiLepCalc         E_{T}^{miss}                  GeV                               'F'    [60.0000343323,1394.23571777]
leptonPt_MultiLepCalc         leptonPt_MultiLepCalc         leptonPt_MultiLepCalc         p_{T}(lep)                    GeV                               'F'    [50.0001716614,1050.66223145]
mass_lepJets0                 mass_lepJets0                 mass_lepJets0                 M(l,j_{1})                    GeV                               'F'    [36.0237045288,3486.60375977]
mass_lepJets1                 mass_lepJets1                 mass_lepJets1                 M(l,j_{2})                    GeV                               'F'    [27.6412391663,2779.77685547]
mass_lepJets2                 mass_lepJets2                 mass_lepJets2                 M(l,j_{3})                    GeV                               'F'    [21.8447246552,2297.85644531]
MT2bb                         MT2bb                         MT2bb                         MT2bb                         GeV                               'F'    [6.34046506882,804.370605469]
mass_lepBJet0                 mass_lepBJet0                 mass_lepBJet0                 M(l,b_{1})                    GeV                               'F'    [21.2006759644,3360.46582031]
mass_lepBJet_mindr            mass_lepBJet_mindr            mass_lepBJet_mindr            M(l,b) with min[#DeltaR(l,b)] GeV                               'F'    [19.0305938721,1970.18225098]
secondJetPt                   secondJetPt                   secondJetPt                   p_{T}(j_{2})                  GeV                               'F'    [32.8107299805,1576.01574707]
fifthJetPt                    fifthJetPt                    fifthJetPt                    p_{T}(j_{5})                  GeV                               'F'    [-1,442.91784668]
sixthJetPt                    sixthJetPt                    sixthJetPt                    p_{T}(j_{6})                  GeV                               'F'    [-1,402.537200928]
PtFifthJet                    PtFifthJet                    PtFifthJet                    5^{th} jet p_{T}              GeV                               'F'    [-1,1919.89807129]
mass_minLLdr                  mass_minLLdr                  mass_minLLdr                  M(j,j) with min[#DeltaR(j,j)], j #neq bGeV                               'F'    [-1,4659.81445312]
mass_maxBBmass                mass_maxBBmass                mass_maxBBmass                max[M(b,b)]                   GeV                               'F'    [18.2635688782,4145.29248047]
deltaR_lepJetInMinMljet       deltaR_lepJetInMinMljet       deltaR_lepJetInMinMljet       #DeltaR(l,j) with min M(l, j)                                   'F'    [0.400007069111,4.35522937775]
deltaPhi_lepJetInMinMljet     deltaPhi_lepJetInMinMljet     deltaPhi_lepJetInMinMljet     #DeltaPhi(l,j) with min M(l, j)                                  'F'    [-3.14141488075,3.14156460762]
deltaR_lepbJetInMinMlb        deltaR_lepbJetInMinMlb        deltaR_lepbJetInMinMlb        #DeltaR(l,b) with min M(l, b)                                   'F'    [0.400013953447,5.16441106796]
deltaPhi_lepbJetInMinMlb      deltaPhi_lepbJetInMinMlb      deltaPhi_lepbJetInMinMlb      #DeltaPhi(l,b) with min M(l, b)                                  'F'    [-3.14146256447,3.14157938957]
M_allJet_W                    M_allJet_W                    M_allJet_W                    M(allJets, leptoninc W)       GeV                               'F'    [532.208007812,8084.01660156]
HT_bjets                      HT_bjets                      HT_bjets                      HT(bjets)                     GeV                               'F'    [50.2371559143,3248.18188477]
ratio_HTdHT4leadjets          ratio_HTdHT4leadjets          ratio_HTdHT4leadjets          HT/HT(4 leading jets)                                           'F'    [1.0077611208,2.62445449829]
csvJet3                       csvJet3                       csvJet3                       DeepCSV(3rdPtJet)                                               'F'    [-2,0.999929070473]
csvJet4                       csvJet4                       csvJet4                       DeepCSV(4thPtJet)                                               'F'    [-2,0.999930858612]
thirdcsvb_bb                  thirdcsvb_bb                  thirdcsvb_bb                  DeepCSV(3rdDeepCSVJet)                                          'F'    [-2,0.999164998531]
fourthcsvb_bb                 fourthcsvb_bb                 fourthcsvb_bb                 DeepCSV(4thDeepCSVJet)                                          'F'    [-2,0.997438132763]
NJets_JetSubCalc              NJets_JetSubCalc              NJets_JetSubCalc              AK4 jet multiplicity                                            'I'    [4,19]
HT_2m                         HT_2m                         HT_2m                         HTwoTwoPtBjets                GeV                               'F'    [60.4830131531,4151.7734375]
Sphericity                    Sphericity                    Sphericity                    Sphericity                    Sphericity                        'F'    [0.000799266039394,0.935396313667]
Aplanarity                    Aplanarity                    Aplanarity                    Aplanarity                    Aplanarity                        'F'    [1.00221654975e-07,0.44571402669]
BDTtrijet1                    BDTtrijet1                    BDTtrijet1                    trijet1 discriminator                                           'F'    [-1,0.999728739262]
BDTtrijet2                    BDTtrijet2                    BDTtrijet2                    trijet2 discriminator                                           'F'    [-1,0.996493160725]
BDTtrijet3                    BDTtrijet3                    BDTtrijet3                    trijet3 discriminator                                           'F'    [-1,0.987466156483]
BDTtrijet4                    BDTtrijet4                    BDTtrijet4                    trijet4 discriminator                                           'F'    [-1,0.941090404987]
NresolvedTops1pFake           NresolvedTops1pFake           NresolvedTops1pFake           resolvedTop multiplicity                                        'F'    [0,3]
NJetsTtagged                  NJetsTtagged                  NJetsTtagged                  top multiplicity                                                'F'    [0,4]
NJetsWtagged                  NJetsWtagged                  NJetsWtagged                  W multiplicity                                                  'F'    [0,4]
NJetsCSVwithSF_JetSubCalc     NJetsCSVwithSF_JetSubCalc     NJetsCSVwithSF_JetSubCalc     bjet multiplicity                                               'F'    [2,9]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 61 )
   {
      // the training input variables
      const char* inputVars[] = { "AK4HTpMETpLepPt", "minMleppBjet", "mass_minBBdr", "deltaR_lepBJet_maxpt", "lepDR_minBBdr", "centrality", "deltaEta_maxBB", "aveCSVpt", "aveBBdr", "FW_momentum_0", "FW_momentum_1", "FW_momentum_2", "FW_momentum_3", "FW_momentum_4", "FW_momentum_5", "FW_momentum_6", "mass_maxJJJpt", "BJetLeadPt", "deltaR_minBB", "minDR_lepBJet", "MT_lepMet", "AK4HT", "hemiout", "theJetLeadPt", "corr_met_MultiLepCalc", "leptonPt_MultiLepCalc", "mass_lepJets0", "mass_lepJets1", "mass_lepJets2", "MT2bb", "mass_lepBJet0", "mass_lepBJet_mindr", "secondJetPt", "fifthJetPt", "sixthJetPt", "PtFifthJet", "mass_minLLdr", "mass_maxBBmass", "deltaR_lepJetInMinMljet", "deltaPhi_lepJetInMinMljet", "deltaR_lepbJetInMinMlb", "deltaPhi_lepbJetInMinMlb", "M_allJet_W", "HT_bjets", "ratio_HTdHT4leadjets", "csvJet3", "csvJet4", "thirdcsvb_bb", "fourthcsvb_bb", "NJets_JetSubCalc", "HT_2m", "Sphericity", "Aplanarity", "BDTtrijet1", "BDTtrijet2", "BDTtrijet3", "BDTtrijet4", "NresolvedTops1pFake", "NJetsTtagged", "NJetsWtagged", "NJetsCSVwithSF_JetSubCalc" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;
      fVmin[19] = 0;
      fVmax[19] = 0;
      fVmin[20] = 0;
      fVmax[20] = 0;
      fVmin[21] = 0;
      fVmax[21] = 0;
      fVmin[22] = 0;
      fVmax[22] = 0;
      fVmin[23] = 0;
      fVmax[23] = 0;
      fVmin[24] = 0;
      fVmax[24] = 0;
      fVmin[25] = 0;
      fVmax[25] = 0;
      fVmin[26] = 0;
      fVmax[26] = 0;
      fVmin[27] = 0;
      fVmax[27] = 0;
      fVmin[28] = 0;
      fVmax[28] = 0;
      fVmin[29] = 0;
      fVmax[29] = 0;
      fVmin[30] = 0;
      fVmax[30] = 0;
      fVmin[31] = 0;
      fVmax[31] = 0;
      fVmin[32] = 0;
      fVmax[32] = 0;
      fVmin[33] = 0;
      fVmax[33] = 0;
      fVmin[34] = 0;
      fVmax[34] = 0;
      fVmin[35] = 0;
      fVmax[35] = 0;
      fVmin[36] = 0;
      fVmax[36] = 0;
      fVmin[37] = 0;
      fVmax[37] = 0;
      fVmin[38] = 0;
      fVmax[38] = 0;
      fVmin[39] = 0;
      fVmax[39] = 0;
      fVmin[40] = 0;
      fVmax[40] = 0;
      fVmin[41] = 0;
      fVmax[41] = 0;
      fVmin[42] = 0;
      fVmax[42] = 0;
      fVmin[43] = 0;
      fVmax[43] = 0;
      fVmin[44] = 0;
      fVmax[44] = 0;
      fVmin[45] = 0;
      fVmax[45] = 0;
      fVmin[46] = 0;
      fVmax[46] = 0;
      fVmin[47] = 0;
      fVmax[47] = 0;
      fVmin[48] = 0;
      fVmax[48] = 0;
      fVmin[49] = 0;
      fVmax[49] = 0;
      fVmin[50] = 0;
      fVmax[50] = 0;
      fVmin[51] = 0;
      fVmax[51] = 0;
      fVmin[52] = 0;
      fVmax[52] = 0;
      fVmin[53] = 0;
      fVmax[53] = 0;
      fVmin[54] = 0;
      fVmax[54] = 0;
      fVmin[55] = 0;
      fVmax[55] = 0;
      fVmin[56] = 0;
      fVmax[56] = 0;
      fVmin[57] = 0;
      fVmax[57] = 0;
      fVmin[58] = 0;
      fVmax[58] = 0;
      fVmin[59] = 0;
      fVmax[59] = 0;
      fVmin[60] = 0;
      fVmax[60] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'F';
      fType[21] = 'F';
      fType[22] = 'F';
      fType[23] = 'F';
      fType[24] = 'F';
      fType[25] = 'F';
      fType[26] = 'F';
      fType[27] = 'F';
      fType[28] = 'F';
      fType[29] = 'F';
      fType[30] = 'F';
      fType[31] = 'F';
      fType[32] = 'F';
      fType[33] = 'F';
      fType[34] = 'F';
      fType[35] = 'F';
      fType[36] = 'F';
      fType[37] = 'F';
      fType[38] = 'F';
      fType[39] = 'F';
      fType[40] = 'F';
      fType[41] = 'F';
      fType[42] = 'F';
      fType[43] = 'F';
      fType[44] = 'F';
      fType[45] = 'F';
      fType[46] = 'F';
      fType[47] = 'F';
      fType[48] = 'F';
      fType[49] = 'I';
      fType[50] = 'F';
      fType[51] = 'F';
      fType[52] = 'F';
      fType[53] = 'F';
      fType[54] = 'F';
      fType[55] = 'F';
      fType[56] = 'F';
      fType[57] = 'F';
      fType[58] = 'F';
      fType[59] = 'F';
      fType[60] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[61];
   double fVmax[61];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[61];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.484382096145103);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.425822, 0, 1, 0.717918,-99) , 
NN(
0, 
0, 
-1, 0.424972, 0, -1, 0.267566,-99) , 
47, 0.285013, 0, 0, 0.50214,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.446631);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.519738, 0, 1, 0.715654,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532404,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.216088,-99) , 
54, 0.520001, 0, 0, 0.31595,-99) , 
60, 2.33333, 0, 0, 0.497169,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.37804);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.710987, 0, 1, 0.700944,-99) , 
NN(
0, 
0, 
-1, 0.330571, 0, -1, 0.333508,-99) , 
48, 0.138534, 0, 0, 0.482925,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.3754);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.520439, 0, 1, 0.659098,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.673361,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.299774,-99) , 
1, 153.263, 0, 0, 0.353111,-99) , 
60, 2.28571, 0, 0, 0.492902,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.297931);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.427887, 0, 1, 0.624974,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513609,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.231254,-99) , 
0, 1076.29, 0, 0, 0.347257,-99) , 
54, 0.330767, 0, 0, 0.484266,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.287978);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.806041, 0, 1, 0.649371,-99) , 
NN(
0, 
0, 
-1, 12.7766, 0, -1, 0.364996,-99) , 
47, 0.427895, 0, 0, 0.46659,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.309975);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 968.939, 0, 1, 0.671407,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579168,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.338216,-99) , 
22, 654.583, 0, 0, 0.399022,-99) , 
54, 0.710987, 0, 0, 0.481903,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.171413);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.763838,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485661,-99) , 
20, 182.054, 0, 0, 0.525893,-99) , 
NN(
0, 
0, 
-1, 136.458, 0, -1, 0.215971,-99) , 
34, 15.5728, 0, 0, 0.480185,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.19546);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.282908, 0, 1, 0.560643,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540407,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.263074,-99) , 
31, 155.913, 0, 0, 0.307161,-99) , 
34, 37.4321, 0, 0, 0.497971,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.201447);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.324977, 0, 1, 0.574914,-99) , 
NN(
0, 
0, 
-1, 1.92786, 0, -1, 0.367013,-99) , 
33, 60.6355, 0, 0, 0.487318,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.273704);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.425602, 0, 1, 0.657583,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.67016,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.380152,-99) , 
55, 0.129733, 0, 0, 0.415463,-99) , 
47, 0.570713, 0, 0, 0.473376,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.220746);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 56.2847, 0, 1, 0.705057,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.623377,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415665,-99) , 
20, 157.965, 0, 0, 0.459676,-99) , 
60, 3.33333, 0, 0, 0.494606,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.23326);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 971.941, 0, 1, 0.660588,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.653822,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410486,-99) , 
31, 155.444, 0, 0, 0.454075,-99) , 
54, 0.806041, 0, 0, 0.500977,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.15577);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.662946,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490309,-99) , 
43, 353.81, 0, 0, 0.543921,-99) , 
NN(
0, 
0, 
-1, 8.73384, 0, -1, 0.294877,-99) , 
49, 6, 0, 0, 0.510267,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.178368);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.282919, 0, 1, 0.664682,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529695,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.373372,-99) , 
30, 138.149, 0, 0, 0.475186,-99) , 
49, 9, 0, 0, 0.521545,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.142217);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.656642,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496068,-99) , 
20, 138.084, 0, 0, 0.54498,-99) , 
NN(
0, 
0, 
-1, 182.85, 0, -1, 0.295228,-99) , 
34, 12.2366, 0, 0, 0.512315,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.130668);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.31981, 0, 1, 0.547102,-99) , 
NN(
0, 
0, 
-1, 138.372, 0, -1, 0.319483,-99) , 
49, 6, 0, 0, 0.516626,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.166273);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 9, 0, 1, 0.672326,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525441,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.377517,-99) , 
48, 0.0660655, 0, 0, 0.469118,-99) , 
48, 0.283563, 0, 0, 0.506065,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.170687);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.700598,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541513,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405538,-99) , 
24, 118.931, 0, 0, 0.467257,-99) , 
55, 0.226226, 0, 0, 0.492525,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.157408);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.703044,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.619682,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445195,-99) , 
47, 0.71353, 0, 0, 0.4689,-99) , 
49, 10, 0, 0, 0.493153,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.142722);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 282.35, 0, 1, 0.572759,-99) , 
NN(
0, 
0, 
-1, 41.2779, 0, -1, 0.431369,-99) , 
54, 0.235712, 0, 0, 0.508394,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.116535);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.900548, 0, 1, 0.544641,-99) , 
NN(
0, 
0, 
-1, 0.0595561, 0, -1, 0.401375,-99) , 
0, 850.64, 0, 0, 0.509174,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.118291);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.726834,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.715999,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466515,-99) , 
29, 136.392, 0, 0, 0.483744,-99) , 
55, 0.419619, 0, 0, 0.500935,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.127112);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.900548, 0, 1, 0.541933,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569152,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.354057,-99) , 
1, 139.051, 0, 0, 0.397546,-99) , 
47, 0.142166, 0, 0, 0.507203,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.158129);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 494.932, 0, 1, 0.668758,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610655,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441057,-99) , 
20, 180.017, 0, 0, 0.466029,-99) , 
54, 0.901096, 0, 0, 0.489545,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.12811);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 9, 0, 1, 0.639332,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.677736,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465455,-99) , 
1, 174.495, 0, 0, 0.484423,-99) , 
48, 0.282919, 0, 0, 0.511984,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.102961);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.711601,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.626461,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477162,-99) , 
58, 0.190476, 0, 0, 0.500489,-99) , 
55, 0.413297, 0, 0, 0.5155,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.110613);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 475.565, 1, 1, 0.580844,-99) , 
NN(
0, 
0, 
-1, 8.70341, 0, -1, 0.469979,-99) , 
22, 519.896, 0, 0, 0.524646,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.128764);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 140.011, 0, 1, 0.576497,-99) , 
NN(
0, 
0, 
-1, 35.0374, 0, -1, 0.453103,-99) , 
52, 0.0410863, 0, 0, 0.52452,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.104026);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 123.537, 0, 1, 0.576045,-99) , 
NN(
0, 
0, 
-1, 34.1358, 0, -1, 0.472701,-99) , 
20, 109.772, 0, 0, 0.524699,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0914112);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 157.78, 0, 1, 0.536634,-99) , 
NN(
0, 
0, 
-1, 1.48524, 0, -1, 0.365863,-99) , 
53, 0.428378, 0, 0, 0.520967,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.131422);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.613012, 0, 1, 0.555532,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.625269,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42845,-99) , 
47, 0.713329, 0, 0, 0.45542,-99) , 
30, 161.361, 0, 0, 0.513552,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0916528);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.6002,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48833,-99) , 
20, 141.9, 0, 0, 0.520754,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.240596,-99) , 
33, 19.5452, 0, 0, 0.510196,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.105313);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.619469, 0, 1, 0.655663,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.621443,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47337,-99) , 
60, 3.33333, 0, 0, 0.494758,-99) , 
29, 116.518, 0, 0, 0.511692,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0989309);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587946,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498066,-99) , 
24, 120.736, 0, 0, 0.536715,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526321,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.33078,-99) , 
44, 1.18021, 0, 0, 0.383501,-99) , 
33, 41.2779, 0, 0, 0.519377,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.113323);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 62.9491, 0, 1, 0.546329,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558346,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408271,-99) , 
1, 139.01, 0, 0, 0.435625,-99) , 
51, 0.177586, 0, 0, 0.517913,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0692026);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.426285, 0, 1, 0.526184,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.246179,-99) , 
33, 17.5646, 0, 0, 0.515897,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.102529);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570464,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472945,-99) , 
5, 0.652187, 0, 0, 0.510203,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.250842,-99) , 
33, 19.5452, 0, 0, 0.500806,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.110018);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 762.324, 0, 1, 0.634052,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542842,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454745,-99) , 
3, 1.53652, 0, 0, 0.490458,-99) , 
54, 0.901096, 0, 0, 0.50727,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0607008);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.425602, 0, 1, 0.518841,-99) , 
NN(
0, 
0, 
-1, 1.07457, 0, -1, 0.349889,-99) , 
53, 0.428181, 0, 0, 0.504077,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0941993);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 170.881, 0, 1, 0.61364,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.631631,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473157,-99) , 
48, 0.42559, 0, 0, 0.488279,-99) , 
1, 149.809, 0, 0, 0.504797,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.119854);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.805521, 0, 1, 0.57946,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562535,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452495,-99) , 
29, 79.792, 0, 0, 0.48105,-99) , 
33, 81.1806, 0, 0, 0.509941,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0746246);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 220.022, 0, 1, 0.527933,-99) , 
NN(
0, 
0, 
-1, 0.853803, 0, -1, 0.394804,-99) , 
49, 6, 0, 0, 0.511892,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0447751);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 775.919, 0, 1, 0.615035,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502791,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.313061,-99) , 
33, 20.1389, 0, 0, 0.495033,-99) , 
54, 0.899672, 0, 0, 0.508845,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0842296);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.520001, 0, 1, 0.588639,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504397,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408294,-99) , 
16, 421.576, 1, 0, 0.472297,-99) , 
58, 0.190476, 0, 0, 0.490157,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0853313);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.636674,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55579,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469507,-99) , 
24, 172.932, 0, 0, 0.488353,-99) , 
55, 0.414876, 0, 0, 0.497995,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.078336);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 164.274, 0, 1, 0.608627,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.606111,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478141,-99) , 
49, 10, 0, 0, 0.490742,-99) , 
20, 193.416, 0, 0, 0.504161,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0868748);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.62581,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577569,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472825,-99) , 
58, 0.142857, 0, 0, 0.489184,-99) , 
48, 0.426285, 0, 0, 0.501652,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0926184);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557149,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484088,-99) , 
37, 215.823, 0, 0, 0.525654,-99) , 
NN(
0, 
0, 
-1, 1.10495, 0, -1, 0.402095,-99) , 
34, 13.3212, 0, 0, 0.511291,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0887342);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55995,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487184,-99) , 
20, 100.196, 0, 0, 0.528766,-99) , 
NN(
0, 
0, 
-1, 0.959567, 0, -1, 0.424728,-99) , 
53, 0.618606, 0, 0, 0.515586,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.104147);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555187,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460213,-99) , 
16, 196.868, 0, 0, 0.5323,-99) , 
NN(
0, 
0, 
-1, 0.332864, 0, -1, 0.446718,-99) , 
16, 529.103, 1, 0, 0.512855,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0444175);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599961,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498865,-99) , 
47, 0.713521, 0, 0, 0.513438,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.331214,-99) , 
53, 0.047355, 0, 0, 0.505344,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0732314);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0374306, 0, 1, 0.549627,-99) , 
NN(
0, 
0, 
-1, 0.142702, 0, -1, 0.473078,-99) , 
52, 0.0606466, 0, 0, 0.505538,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0728057);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55921,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490315,-99) , 
24, 120.736, 0, 0, 0.520565,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.325778,-99) , 
33, 19.5452, 0, 0, 0.51387,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.104797);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573829,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496899,-99) , 
36, 69.0433, 0, 0, 0.539872,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544803,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420102,-99) , 
19, 1.24139, 0, 0, 0.468471,-99) , 
54, 0.140489, 0, 0, 0.510926,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0617117);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.936751, 0, 1, 0.604969,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578342,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488995,-99) , 
5, 0.768582, 0, 0, 0.502636,-99) , 
54, 0.900548, 0, 0, 0.514292,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0782546);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 223.801, 0, 1, 0.531021,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528987,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.362897,-99) , 
19, 1.53684, 0, 0, 0.410131,-99) , 
33, 41.2779, 0, 0, 0.51814,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0604696);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 644.147, 0, 1, 0.523066,-99) , 
NN(
0, 
0, 
-1, 0.0394023, 0, -1, 0.447156,-99) , 
47, 0.142261, 0, 0, 0.504885,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0771303);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.614033,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522463,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392656,-99) , 
48, 0.0375261, 0, 0, 0.506991,-99) , 
47, 0.856266, 0, 0, 0.514756,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0675601);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.618198,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553347,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476439,-99) , 
43, 507.458, 0, 0, 0.487223,-99) , 
55, 0.414876, 0, 0, 0.495898,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0549555);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.808592, 0, 1, 0.597957,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583098,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487445,-99) , 
1, 151.335, 0, 0, 0.498672,-99) , 
20, 209.315, 0, 0, 0.507189,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0794342);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.684414,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477368,-99) , 
20, 108.983, 0, 0, 0.572657,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513801,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453935,-99) , 
51, 0.22392, 0, 0, 0.493553,-99) , 
24, 177.863, 0, 0, 0.50986,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0702289);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 128.883, 0, 1, 0.588615,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526217,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46914,-99) , 
29, 42.1599, 0, 0, 0.500841,-99) , 
54, 0.901096, 0, 0, 0.510698,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.06028);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523805,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468174,-99) , 
16, 456.604, 1, 0, 0.507171,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.358202,-99) , 
33, 19.5452, 0, 0, 0.502145,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.072512);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599956,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525225,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46357,-99) , 
7, 0.728096, 1, 0, 0.493702,-99) , 
47, 0.856348, 0, 0, 0.501769,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0683547);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 10, 0, 1, 0.524085,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54119,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440599,-99) , 
20, 141.901, 0, 0, 0.466896,-99) , 
37, 184.801, 0, 0, 0.505295,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0612647);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603513,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517042,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464036,-99) , 
40, 1.05603, 0, 0, 0.493234,-99) , 
55, 0.414083, 0, 0, 0.500381,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0735752);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584792,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525465,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463256,-99) , 
3, 1.76385, 0, 0, 0.484474,-99) , 
47, 0.856348, 0, 0, 0.491868,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0344294);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.60072,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498781,-99) , 
20, 209.315, 0, 0, 0.506942,-99) , 
NN(
0, 
0, 
-1, 0.792494, 0, -1, 0.413725,-99) , 
53, 0.523603, 0, 0, 0.49724,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.068317);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54514,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495231,-99) , 
36, 65.0012, 0, 0, 0.52527,-99) , 
NN(
0, 
0, 
-1, 0.853778, 0, -1, 0.456755,-99) , 
54, 0.0451062, 0, 0, 0.500923,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.056338);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.939874, 0, 1, 0.563301,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507572,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443928,-99) , 
8, 1.88592, 0, 0, 0.492491,-99) , 
10, 0.324951, 0, 0, 0.507017,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0369921);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 89.7783, 1, 1, 0.583569,-99) , 
NN(
0, 
0, 
-1, 0.61864, 0, -1, 0.488962,-99) , 
29, 116.793, 0, 0, 0.49868,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0779433);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567031,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431133,-99) , 
14, 0.340443, 1, 0, 0.550171,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543982,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472464,-99) , 
5, 0.735081, 0, 0, 0.489354,-99) , 
10, 0.322403, 0, 0, 0.502036,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0759243);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541133,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473886,-99) , 
29, 28.1224, 0, 0, 0.521333,-99) , 
NN(
0, 
0, 
-1, 0.71373, 0, -1, 0.458149,-99) , 
8, 1.85584, 0, 0, 0.506847,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.045948);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 67.2244, 0, 1, 0.516656,-99) , 
NN(
0, 
0, 
-1, 1.17418, 0, -1, 0.383807,-99) , 
53, 0.237927, 0, 0, 0.508246,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0823417);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.627137,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471927,-99) , 
24, 123.536, 0, 0, 0.543065,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553774,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474606,-99) , 
21, 1205.76, 0, 0, 0.486705,-99) , 
20, 146.873, 0, 0, 0.501324,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.027993);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.502779, 0, 1, 0.509133,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.335897,-99) , 
33, 19.5452, 0, 0, 0.5037,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0751956);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 181.125, 0, 1, 0.533224,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540982,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460677,-99) , 
48, 0.280941, 0, 0, 0.476076,-99) , 
29, 71.3139, 0, 0, 0.494901,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0352682);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576053,-99) , 
NN(
0, 
0, 
-1, 674.31, 1, -1, 0.488805,-99) , 
49, 10, 0, 0, 0.497456,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0355271);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 207.672, 0, 1, 0.512161,-99) , 
NN(
0, 
0, 
-1, 0.714218, 0, -1, 0.413244,-99) , 
53, 0.332997, 0, 0, 0.504741,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0518502);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593207,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507057,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453909,-99) , 
20, 91.2003, 0, 0, 0.488216,-99) , 
20, 223.801, 0, 0, 0.495487,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0443078);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.905394, 0, 1, 0.564608,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579447,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487333,-99) , 
5, 0.841633, 0, 0, 0.492882,-99) , 
54, 0.899666, 0, 0, 0.501039,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0612502);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541247,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48863,-99) , 
40, 1.2747, 0, 0, 0.511492,-99) , 
NN(
0, 
0, 
-1, 0.0127049, 0, -1, 0.444484,-99) , 
52, 0.020523, 0, 0, 0.498086,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0611278);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.296044, 1, 1, 0.58204,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544321,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480747,-99) , 
24, 172.354, 0, 0, 0.495019,-99) , 
44, 1.54845, 0, 0, 0.503614,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0565757);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531607,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484264,-99) , 
25, 91.7381, 1, 0, 0.509956,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384733,-99) , 
53, 0.0473331, 0, 0, 0.504573,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.037613);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.31996, 0, 1, 0.515626,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.385971,-99) , 
33, 20.1389, 0, 0, 0.511447,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0402331);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.640862,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488106,-99) , 
20, 100.686, 0, 0, 0.56426,-99) , 
NN(
0, 
0, 
-1, 111.054, 0, -1, 0.48899,-99) , 
24, 206.669, 0, 0, 0.499493,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0493634);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 7, 1, 1, 0.524972,-99) , 
NN(
0, 
0, 
-1, 1.12624, 0, -1, 0.475909,-99) , 
54, 0.0454484, 0, 0, 0.507692,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0401487);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.713329, 0, 1, 0.516169,-99) , 
NN(
0, 
0, 
-1, 0.020469, 0, -1, 0.453287,-99) , 
18, 0.757814, 0, 0, 0.508151,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0475641);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.905714, 0, 1, 0.51404,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522757,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422527,-99) , 
10, 0.317795, 0, 0, 0.444301,-99) , 
22, 392.35, 0, 0, 0.500884,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0511463);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569639,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535707,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481191,-99) , 
48, 0.280138, 0, 0, 0.491526,-99) , 
1, 178.813, 0, 0, 0.497329,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0610219);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 708.733, 0, 1, 0.563905,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53837,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480424,-99) , 
10, 0.276353, 0, 0, 0.495257,-99) , 
58, 0.190476, 0, 0, 0.505829,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0490116);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583324,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518767,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477739,-99) , 
23, 261.386, 1, 0, 0.500893,-99) , 
55, 0.419084, 0, 0, 0.506382,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0309718);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572969,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499667,-99) , 
55, 0.229873, 0, 0, 0.507598,-99) , 
NN(
0, 
0, 
-1, 740.528, 0, -1, 0.444935,-99) , 
22, 379.591, 0, 0, 0.497853,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0352955);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592859,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507159,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450362,-99) , 
18, 0.777484, 0, 0, 0.49951,-99) , 
20, 233.746, 0, 0, 0.505067,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0479977);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578021,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541355,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48677,-99) , 
26, 200.337, 1, 0, 0.49974,-99) , 
22, 916.816, 0, 0, 0.50522,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0294758);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595177,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501492,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434001,-99) , 
16, 666.345, 1, 0, 0.492628,-99) , 
20, 233.745, 0, 0, 0.498369,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0512682);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.605,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51811,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474485,-99) , 
2, 163.619, 0, 0, 0.494175,-99) , 
20, 255.93, 0, 0, 0.498776,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0390242);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.13437, 0, 1, 0.549493,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50514,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446317,-99) , 
22, 393.309, 0, 0, 0.493982,-99) , 
47, 0.713215, 0, 0, 0.502124,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0403543);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603251,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56103,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486714,-99) , 
47, 0.856348, 0, 0, 0.492164,-99) , 
20, 259.087, 0, 0, 0.496506,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
            retval = GetMvaValue__( inputValues );
      }

      return retval;
   }
