universe = vanilla
Executable = /user_data/jlee/TTTT/CMSSW_9_4_6_patch1/src/TMVA/doCondorApplication.sh
Should_Transfer_Files = YES
WhenToTransferOutput = ON_EXIT
request_memory = 3072
Transfer_Input_Files = /user_data/jlee/TTTT/CMSSW_9_4_6_patch1/src/TMVA/LJMet94X_1lepTT_022719_step2_saraBDay_BDT_BigComb_3var_condorLogs/nominal//TMVAClassificationApplication.C
Output = QCD_HT300to500_TuneCP5_13TeV-madgraph-pythia8_hadd.out
Error = QCD_HT300to500_TuneCP5_13TeV-madgraph-pythia8_hadd.err
Log = QCD_HT300to500_TuneCP5_13TeV-madgraph-pythia8_hadd.log
Notification = Never
Arguments = /isilon/hadoop/store/user/mhadley/TTTT/LJMet94X_1lepTT_022719_step2_saraBDay/nominal/ /isilon/hadoop/store/user/jblee/TTTT/LJMet94X_1lepTT_022719_step2_saraBDay_BDT_BigComb_3var/nominal/ QCD_HT300to500_TuneCP5_13TeV-madgraph-pythia8_hadd.root BDT /user_data/jlee/TTTT/CMSSW_9_4_6_patch1/src/TMVA/LJMet94X_1lepTT_022719_step2_saraBDay_BDT_BigComb_3var_condorLogs/nominal/

Queue 1